SHELL=/bin/bash

#PYTHON_BUILD=/Library/Frameworks/Python.framework/Versions/2.7
PYTHON_BUILD=/usr/local
#PYTHON_VENV=/Users/dandicara/Documents/python_virtualenvs/python_venv_dev
PYTHON_VENV=/home/ddicara/Documents/python_virtualenvs/python_venv_dev
